spring.application.name=stadiumManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/stadium_db
spring.datasource.username=postgres
spring.datasource.password=cedric123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

ama.app.jwtSecret=AmahoroStadiumManagementSystemSecretKeyForHS256Algorithm32Chars
ama.app.jwtExpirationMs=86400000
